-- ========== 고객 데이터 삽입 ==========
INSERT INTO customers (company_name) VALUES ('한양기공') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('천지공조시스템') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('엘에스시스템공조') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('메이필드 호텔') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('주식회사 크라스') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('교원그룹') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('동현기계설비') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('HD디자인') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('삼성전자') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('주식회사 넥스트페이먼츠') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('삼성생명공익재단삼성노블카운티') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('오스템임플란트') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('태원산업개발') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('천지수왕사') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('메가커피 서초브라운스톤점') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('글루온투자증권') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('(주)미래인베스트먼트') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('삼성생명서비스손해사정(주)') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('애플산부인과') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('롯데리아 중앙대점') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('에드이엔씨') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('(주)와이엠팜_마리보인웨이브') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('별빛 호텔') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('주)행복가든 라크렘산후조리원') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('페리카나 치킨 도봉구점') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('신세계토건') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('삼성전자 로지텍 김창숙 프로') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('(주)신안관광') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('슬로우캘리 왕십리뉴타운점') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('르와르빌 102호') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('원주 다올산후조리원') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('원인숙 상무님_군장종합건설') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('메머드익스프레스 금정역점') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('서울시니어스타워(주) 고창웰파크시티') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('주식회사 쓱싹') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('(주)천명') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('주와그리스도교회') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('플랜잇웍스') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('하이큐시스템') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('현대기술산업') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('하이공조') ON CONFLICT DO NOTHING;
INSERT INTO customers (company_name) VALUES ('아이마켓코리아') ON CONFLICT DO NOTHING;

-- ========== 의뢰 데이터 삽입 ==========
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('해월리 피정센터_한양기공', 'KRW', '2025-02-12', '견적 문의', (SELECT id FROM customers WHERE company_name = '한양기공' LIMIT 1), '기본 폴더', '2025-02-12 17:51:06');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('유상 공장 시스템에어컨 공사', 'KRW', '2025-02-07', '수주 실패', (SELECT id FROM customers WHERE company_name = '천지공조시스템' LIMIT 1), '기본 폴더', '2025-02-07 16:44:07');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('(엘에스솔루션)봉천동 862-7, 9근생 업무 신축공사(EHP,전열교환기)', 'KRW', '2025-01-22', '수주 실패', (SELECT id FROM customers WHERE company_name = '엘에스시스템공조' LIMIT 1), '기본 폴더', '2025-01-22 09:19:57');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('메이필드호텔 매립덕트 교체공사', 'KRW', '2025-01-14', '계약 성공', (SELECT id FROM customers WHERE company_name = '메이필드 호텔' LIMIT 1), '기본 폴더', '2025-01-23 17:35:40');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('사회복지법인', 'KRW', '2025-02-18', '영업중', NULL, '기본 폴더', '2025-02-18 13:50:44');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('크라스 공청판넬 교체건', 'KRW', '2024-12-02', '계약 성공', (SELECT id FROM customers WHERE company_name = '주식회사 크라스' LIMIT 1), '기본 폴더', '2025-01-20 11:23:34');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('교원 위즈 직영학원 냉난방기 분해세척 견적서', 'KRW', '2025-03-20', '견적 문의', NULL, '기본 폴더', '2025-03-20 13:25:08');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('미추홀구 노인복지관 에어컨 리모델링 공사건', 'KRW', '2025-03-28', '견적 문의', NULL, '기본 폴더', '2025-03-28 18:15:15');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('교원 투어빌딩 실외기 이전설치', 'KRW', '2025-03-21', '견적 문의', NULL, '기본 폴더', '2025-03-21 10:15:55');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 2월', 'KRW', '2024-02-01', '계약 성공', (SELECT id FROM customers WHERE company_name = '교원그룹' LIMIT 1), '기본 폴더', '2025-01-20 19:34:44');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 1월', 'KRW', '2024-01-01', '계약 성공', (SELECT id FROM customers WHERE company_name = '교원그룹' LIMIT 1), '기본 폴더', '2025-01-20 19:32:42');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 4월', 'KRW', '2024-04-01', '계약 성공', NULL, '기본 폴더', '2025-01-20 19:37:45');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 9월', 'KRW', '2024-09-01', '계약 성공', NULL, '기본 폴더', '2025-01-20 19:42:48');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 12월 교원그룹', 'KRW', '2024-12-01', '계약 성공', NULL, '기본 폴더', '2025-01-20 19:46:23');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('서울시립영보노인요양원 시스템에어컨 납품건', 'KRW', '2024-03-06', '계약 성공', (SELECT id FROM customers WHERE company_name = '동현기계설비' LIMIT 1), '기본 폴더', '2025-01-17 23:34:32');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 8월', 'KRW', '2024-08-01', '계약 성공', NULL, '기본 폴더', '2025-01-20 19:41:38');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('HD디자인 사무실 에어컨 교체공사', 'KRW', '2025-05-15', '계약 성공', (SELECT id FROM customers WHERE company_name = 'HD디자인' LIMIT 1), '기본 폴더', '2025-05-15 09:22:58');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('2024년 장려금', 'KRW', '2024-12-31', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성전자' LIMIT 1), '기본 폴더', '2025-01-20 19:15:16');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 7월', 'KRW', '2024-07-01', '계약 성공', NULL, '기본 폴더', '2025-01-20 19:40:39');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('용산 무인샐러드샵 냉난방기 납품건', 'KRW', '2024-11-07', '계약 성공', (SELECT id FROM customers WHERE company_name = '주식회사 넥스트페이먼츠' LIMIT 1), '기본 폴더', '2025-01-17 23:45:29');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('노블카운티  냉난방기 추가공사', 'KRW', '2024-11-29', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성생명공익재단삼성노블카운티' LIMIT 1), '기본 폴더', '2025-01-20 10:55:16');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('오스템임플란트 A.B동 통합빌딩제어공사', 'KRW', '2024-08-08', '계약 성공', (SELECT id FROM customers WHERE company_name = '오스템임플란트' LIMIT 1), '기본 폴더', '2025-01-20 11:27:46');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('가든파이브툴 FCU 교체 추가공사건', 'KRW', '2024-08-05', '계약 성공', (SELECT id FROM customers WHERE company_name = '태원산업개발' LIMIT 1), '기본 폴더', '2025-01-17 23:43:55');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 6월', 'KRW', '2024-06-01', '계약 성공', NULL, '기본 폴더', '2025-01-20 19:39:46');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('노블카운티 너싱홈 냉난방기 납품건', 'KRW', '2024-07-12', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성생명공익재단삼성노블카운티' LIMIT 1), '기본 폴더', '2025-01-17 23:41:50');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('천지수왕사 본관 추가 냉난방기 납품건', 'KRW', '2024-07-08', '계약 성공', (SELECT id FROM customers WHERE company_name = '천지수왕사' LIMIT 1), '기본 폴더', '2025-01-17 23:41:22');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('메가커피 서초브라운점 냉난방기 납품건', 'KRW', '2024-06-10', '계약 성공', (SELECT id FROM customers WHERE company_name = '메가커피 서초브라운스톤점' LIMIT 1), '기본 폴더', '2025-01-17 23:40:21');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('여의도 글루온투자 증권 냉난방기 납품건', 'KRW', '2024-06-03', '계약 성공', (SELECT id FROM customers WHERE company_name = '글루온투자증권' LIMIT 1), '기본 폴더', '2025-01-17 23:39:14');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('노블카운티 A동 3대 신규설치공사', 'KRW', '2025-03-04', '견적 문의', (SELECT id FROM customers WHERE company_name = '삼성생명공익재단삼성노블카운티' LIMIT 1), '기본 폴더', '2025-03-04 09:11:26');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('메머드커피 계약단가', 'KRW', '2025-03-20', '견적 문의', NULL, '기본 폴더', '2025-03-20 11:15:47');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('하워드존슨 호텔_영종도_1번째공사', 'KRW', '2025-05-12', '계약 성공', (SELECT id FROM customers WHERE company_name = '(주)미래인베스트먼트' LIMIT 1), '기본 폴더', '2025-05-12 10:21:42');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('삼성생명 에어컨 설치공사', 'KRW', '2025-04-10', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성생명서비스손해사정(주)' LIMIT 1), '기본 폴더', '2025-04-10 15:01:01');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('삼성생명 평촌플라자 탕비실 냉난방 설치공사', 'KRW', '2025-05-22', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성생명서비스손해사정(주)' LIMIT 1), '기본 폴더', '2025-05-22 16:19:27');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('서서울로지텍 에어컨 공사', 'KRW', '2025-04-29', '견적 문의', NULL, '기본 폴더', '2025-04-29 17:59:50');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('애플산부인과 추가 증설', 'KRW', '2025-06-04', '계약 성공', (SELECT id FROM customers WHERE company_name = '애플산부인과' LIMIT 1), '기본 폴더', '2025-06-04 16:19:43');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('롯데리아 중앙대점', 'KRW', '2025-06-17', '계약 성공', (SELECT id FROM customers WHERE company_name = '롯데리아 중앙대점' LIMIT 1), '기본 폴더', '2025-06-17 13:17:38');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 5월', 'KRW', '2024-05-01', '계약 성공', NULL, '기본 폴더', '2025-01-20 19:38:50');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 10월', 'KRW', '2024-10-01', '계약 성공', (SELECT id FROM customers WHERE company_name = '교원그룹' LIMIT 1), '기본 폴더', '2025-01-20 19:43:54');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 3월', 'KRW', '2024-03-01', '계약 성공', (SELECT id FROM customers WHERE company_name = '교원그룹' LIMIT 1), '기본 폴더', '2025-01-20 19:36:13');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('주안동 다세대주택 DVM HOME 납품건', 'KRW', '2023-12-13', '계약 성공', (SELECT id FROM customers WHERE company_name = '에드이엔씨' LIMIT 1), '기본 폴더', '2025-01-17 23:32:45');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원그룹 11월', 'KRW', '2024-11-01', '계약 성공', (SELECT id FROM customers WHERE company_name = '교원그룹' LIMIT 1), '기본 폴더', '2025-01-20 19:45:11');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('노블카운티 2F,3F 냉난방기 납품건', 'KRW', '2024-06-13', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성생명공익재단삼성노블카운티' LIMIT 1), '기본 폴더', '2025-01-17 23:42:45');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('마레보인웨이브 스탠드형 추가설치건', 'KRW', '2025-05-22', '계약 성공', (SELECT id FROM customers WHERE company_name = '(주)와이엠팜_마리보인웨이브' LIMIT 1), '기본 폴더', '2025-05-22 15:07:04');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('별빛호텔 시스템에어컨 교체 공사건', 'KRW', '2024-07-26', '계약 성공', (SELECT id FROM customers WHERE company_name = '별빛 호텔' LIMIT 1), '기본 폴더', '2025-01-17 23:41:02');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('라크렘 산후조리원 냉난방기 납품건', 'KRW', '2024-09-25', '계약 성공', (SELECT id FROM customers WHERE company_name = '주)행복가든 라크렘산후조리원' LIMIT 1), '기본 폴더', '2025-01-17 23:44:46');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('오스템임플란트 동물실험실 시스템에어컨 납품건', 'KRW', '2024-03-08', '계약 성공', (SELECT id FROM customers WHERE company_name = '오스템임플란트' LIMIT 1), '기본 폴더', '2025-01-17 23:35:40');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('페리카나치킨 도봉구점 장비교체 공사', 'KRW', '2025-01-01', '계약 성공', (SELECT id FROM customers WHERE company_name = '페리카나 치킨 도봉구점' LIMIT 1), '기본 폴더', '2025-01-17 15:11:50');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('24년 교원 장려금', 'KRW', '2024-12-31', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성전자' LIMIT 1), '기본 폴더', '2025-01-20 19:55:35');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('신세계 토건 황성호 이사님 견적요청건', 'KRW', '2025-01-22', '계약 성공', (SELECT id FROM customers WHERE company_name = '신세계토건' LIMIT 1), '기본 폴더', '2025-01-22 13:24:56');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('가든파이브툴 fcu  5층 교체공사', 'KRW', '2024-04-25', '계약 성공', (SELECT id FROM customers WHERE company_name = '태원산업개발' LIMIT 1), '기본 폴더', '2025-01-17 23:36:11');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('로지텍 싱글 기기교체 공사', 'KRW', '2025-02-04', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성전자 로지텍 김창숙 프로' LIMIT 1), '기본 폴더', '2025-02-04 11:37:23');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('애플산부인과 시스템에어컨 납품건', 'KRW', '2024-08-02', '계약 성공', (SELECT id FROM customers WHERE company_name = '애플산부인과' LIMIT 1), '기본 폴더', '2025-01-17 23:44:19');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('청담 리베라호텔 에어컨 설치공사', 'KRW', '2025-05-14', '계약 성공', (SELECT id FROM customers WHERE company_name = '(주)신안관광' LIMIT 1), '기본 폴더', '2025-05-14 09:24:58');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('슬로우캘리 왕십리뉴타운점', 'KRW', '2025-07-31', '계약 성공', (SELECT id FROM customers WHERE company_name = '슬로우캘리 왕십리뉴타운점' LIMIT 1), '기본 폴더', '2025-07-31 10:29:10');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('천지공조_성남AK플라자', 'KRW', '2025-06-19', '계약 성공', (SELECT id FROM customers WHERE company_name = '천지공조시스템' LIMIT 1), '기본 폴더', '2025-06-19 16:23:47');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('용산구 한남대로 8길 6-28 (르와르빌 102호)', 'KRW', '2025-07-22', '계약 성공', (SELECT id FROM customers WHERE company_name = '르와르빌 102호' LIMIT 1), '기본 폴더', '2025-07-22 16:45:48');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('하워드존슨호텔 이전설치건', 'KRW', '2025-09-08', '계약 성공', (SELECT id FROM customers WHERE company_name = '(주)미래인베스트먼트' LIMIT 1), '기본 폴더', '2025-09-08 10:24:12');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('원주 다올산후조리원 기기교체건', 'KRW', '2025-07-31', '계약 성공', (SELECT id FROM customers WHERE company_name = '원주 다올산후조리원' LIMIT 1), '기본 폴더', '2025-07-31 09:26:20');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('군산 수송 오투그란데 302동 301호', 'KRW', '2025-07-22', '계약 성공', (SELECT id FROM customers WHERE company_name = '원인숙 상무님_군장종합건설' LIMIT 1), '기본 폴더', '2025-07-22 09:06:41');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('메머드커피 금정역점', 'KRW', '2025-04-15', '계약 성공', (SELECT id FROM customers WHERE company_name = '메머드익스프레스 금정역점' LIMIT 1), '기본 폴더', '2025-04-15 15:22:30');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('마레보인 웨이브 냉난방 설치공사', 'KRW', '2025-05-14', '계약 성공', (SELECT id FROM customers WHERE company_name = '(주)와이엠팜_마리보인웨이브' LIMIT 1), '기본 폴더', '2025-05-14 09:27:37');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('전북 고창군 고창읍 석정2로 233 기기교체', 'KRW', '2025-02-04', '계약 성공', (SELECT id FROM customers WHERE company_name = '서울시니어스타워(주) 고창웰파크시티' LIMIT 1), '기본 폴더', '2025-02-04 14:47:51');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('강화도 전원주택 2채 시스템에어컨 납품건', 'KRW', '2024-11-20', '계약 성공', (SELECT id FROM customers WHERE company_name = '에드이엔씨' LIMIT 1), '기본 폴더', '2025-01-17 23:45:55');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('(쓱싹)산본프라자 장비납품건', 'KRW', '2025-05-15', '계약 성공', (SELECT id FROM customers WHERE company_name = '주식회사 쓱싹' LIMIT 1), '기본 폴더', '2025-05-15 09:04:38');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('하워드존슨 호텔 추가공사건_2번째공사', 'KRW', '2025-05-26', '계약 성공', (SELECT id FROM customers WHERE company_name = '(주)미래인베스트먼트' LIMIT 1), '기본 폴더', '2025-05-26 15:35:43');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('가든파이브툴 9F,10F 시스템에어컨 납품', 'KRW', '2024-05-03', '계약 성공', (SELECT id FROM customers WHERE company_name = '(주)천명' LIMIT 1), '기본 폴더', '2025-01-17 23:38:23');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('주와그리스도교회 냉난방기기 설치', 'KRW', '2025-05-13', '계약 성공', (SELECT id FROM customers WHERE company_name = '주와그리스도교회' LIMIT 1), '기본 폴더', '2025-05-13 17:53:33');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('노블카운티 너싱홈 주방 스탠드1대 추가공사건_너싱홈', 'KRW', '2024-11-21', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성생명공익재단삼성노블카운티' LIMIT 1), '기본 폴더', '2025-01-17 23:46:17');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('더 마레보호텔 지하1F 추가설치건', 'KRW', '2024-05-02', '계약 성공', (SELECT id FROM customers WHERE company_name = '플랜잇웍스' LIMIT 1), '기본 폴더', '2025-01-17 23:37:49');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('메리어트호텔 냉난방 설치공사(지하1층,1층,2층)', 'KRW', '2025-07-22', '계약 성공', (SELECT id FROM customers WHERE company_name = '하이큐시스템' LIMIT 1), '기본 폴더', '2025-07-22 16:24:33');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('성균관대학교 국제관 냉난방기 교체건', 'KRW', '2025-09-02', '계약 성공', (SELECT id FROM customers WHERE company_name = '현대기술산업' LIMIT 1), '기본 폴더', '2025-09-02 12:58:53');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('천지수왕사 A.B동 냉난방기 납품건', 'KRW', '2024-07-01', '계약 성공', (SELECT id FROM customers WHERE company_name = '천지수왕사' LIMIT 1), '기본 폴더', '2025-01-17 23:40:38');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('동서울 1층 천정형 에어컨 철거공사 및 드레인수정', 'KRW', '2025-09-09', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성전자 로지텍 김창숙 프로' LIMIT 1), '기본 폴더', '2025-09-09 09:42:15');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('한양기공_영등동 목욕탕 EHP 설치공사', 'KRW', '2025-11-26', '견적 문의', (SELECT id FROM customers WHERE company_name = '한양기공' LIMIT 1), '기본 폴더', '2025-11-26 09:10:24');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('삼성전자 로지텍 서서울물류센터 3대 기기교체', 'KRW', '2025-11-20', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성전자 로지텍 김창숙 프로' LIMIT 1), '기본 폴더', '2025-11-20 11:31:19');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('현대기술산업 ERV 납품건', 'KRW', '2025-12-04', '계약 성공', (SELECT id FROM customers WHERE company_name = '현대기술산업' LIMIT 1), '기본 폴더', '2025-12-04 14:43:02');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('교원그룹', 'KRW', '2025-08-04', '견적 문의', NULL, '기본 폴더', '2025-08-04 15:48:13');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('하이공조 랩스테이션 8층 EHP 장비납품', 'KRW', '2025-12-29', '계약 성공', (SELECT id FROM customers WHERE company_name = '하이공조' LIMIT 1), '기본 폴더', '2025-12-29 09:43:09');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('삼성생명 천안지점 EHP 설치공사', 'KRW', '2025-12-29', '계약 성공', (SELECT id FROM customers WHERE company_name = '삼성생명서비스손해사정(주)' LIMIT 1), '기본 폴더', '2025-12-29 09:46:55');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('교원 내외빌딩 EHP 설치공사', 'KRW', '2025-11-03', '계약 성공', (SELECT id FROM customers WHERE company_name = '교원그룹' LIMIT 1), '기본 폴더', '2025-11-03 14:42:47');
INSERT INTO requests (title, currency, inquiry_date, status, customer_id, folder, created_at) VALUES ('영종도 자이아파트 헬스장 (아이마켓코리아)+(에스원)', 'KRW', '2026-01-13', '계약 성공', (SELECT id FROM customers WHERE company_name = '아이마켓코리아' LIMIT 1), '기본 폴더', '2026-01-13 09:17:25');
